### ISSUE TITLE
Source Code for Extension

### ISSUE THREAD

**Issue by carceneaux** [rubrikinc/rubrik-extension-for-vcd#21]
**What would you like to be added**:

I'd like for the source code to the Rubrik vCD Extension to be publicly accessible. Currently, only the bundled version of the plugin is accessible.

**Why is this needed**:

Per Rubrik, the plugin is simply leveraging Rubrik's **awesome** APIs. As a MSP, I'd like to see what's going on in this plugin behind the scenes as well as have the ability to validate the credentials being stored on the provider portal side are indeed secure.

Thanks for creating this plugin! It's awesome!

**Comment by Draper1** [comment]
@carceneaux Thanks for the feedback!

We are indeed considering releasing the source code and are just ensuring its vetted correctly before it's published.

In the meantime, just to confirm the credentials being stored within metadata; we use an internal vCD value to salt and hash the credentials being stored and use the following encryption standards:

* Keysize: AES256
* Mode: CBC
* Padding: PKCS7

The metadata is written also written as a READONLY value; the reason to use metadata as storage, was a decision we made to remove a requirement with maintaining a database on the vCD Cell side, and also so that it's an isolated place that other tenants cannot see metadata across tenants or at the provider level.

**Comment by Draper1** [comment]
This has been added to the road map. Closing Request.
